# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_graphics.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1000, 640)
        Frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.graphicsView = QtWidgets.QGraphicsView(Frame)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 1000, 640))
        self.graphicsView.setMinimumSize(QtCore.QSize(128, 128))
        self.graphicsView.setMaximumSize(QtCore.QSize(16000, 16000))
        self.graphicsView.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setTransformationAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.graphicsView.setViewportUpdateMode(QtWidgets.QGraphicsView.SmartViewportUpdate)
        self.graphicsView.setObjectName("graphicsView")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
